[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Configurazione webhook per Netlify Forms
[[plugins]]
  package = "@netlify/plugin-emails"

# Webhook per form submissions
[forms]
  webhook = "/.netlify/functions/form-webhook"

# Redirects per le pagine di successo - devono reindirizzare all'index.html per React Router
[[redirects]]
  from = "/success-preventivo*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success-checkup*"
  to = "/index.html"
  status = 200

# Login page
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing (deve essere l'ultimo)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurazione per il caching di risorse statiche
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
